[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node_modules/.bin/prisma db push && node_modules/.bin/prisma db seed && npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
